### ISSUE TITLE
Allow space in tags

### ISSUE THREAD

**Issue by MatElGran** [Rurik19/wallabagger#2]
It would be great if it were possible to add tags containing space. I see in the code that a tag is submitted when hitting either space, comma, or semi-colon. 

I wouldn't mind losing submission on hitting space in favor of tags with spaces, but some might love it, so maybe a configuration allowing to disable individual submission keys would fit.

Anyway, thanks for the great work, using it everyday

**Comment by Rurik19** [comment]
Maybe enter key instead of space? (with option in setup).
