### ISSUE TITLE
Keyboard Shortcuts ?

### ISSUE THREAD

**Issue by jcherqui** [Rurik19/wallabagger#5]
Hello,

I would like to know if there is keyboard shortcuts for add an entry instead of click with mouse on widget button ?

Thank you for your work !

**Comment by Rurik19** [comment]
Not yet....

**Comment by Rurik19** [comment]
From Chrome Documentation:

> The user is free to designate any shortcut as global using the UI in chrome://extensions \ Keyboard Shortcuts

I tries this, and it works

**Comment by jcherqui** [comment]
Awesome ! Thanks ;)
